spring:
  # Common configurations for all profiles
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    # Default (common) database configurations
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1

# Development-specific database configuration
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}

# Production-specific database configuration
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}

api:
  key: ${EDAMAM_API_KEY}
email:
  address: ${GMAIL_ADDRESS}
