spring:
  profiles:
    active: development
  security:
    user:
      name: user
      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'INSERT_USERNAME_HERE'
    password: 'INSERT_PASSWORD_HERE'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  key: 'INSERT_EDAMAM_API_KEY_HERE'
email:
  address: 'INSERT_EMAIL_ADDRESS_HERE'