spring:
  profiles:
    active: development
  security:
    user:
      name: user
      password: password
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: success01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
